// Generated by apps/worker-audio-extraction/scripts/export-languages.py. Do not edit.
//
// Source: capabilities.transcription_languages() in
// apps/worker-audio-extraction/src/audio_extraction/capabilities.py, evaluated with
// WhisperX 3.8.6 (whisperx/utils.py LANGUAGES and whisperx/alignment.py alignment
// models) and the default multilingual model, filtered to OFFERED in that script
// (the app's shorter list, in display order). A deployed worker built from other
// code can differ; it then rejects the language when the transcription job runs.
//
// Regenerate after changing capabilities.py or the WhisperX pin in uv.lock:
//   uv run --no-project --with pip python apps/worker-audio-extraction/scripts/export-languages.py \
//       > apps/client-macos-swift/Sources/GdayMeetings/Services/RunPodLanguages.swift

enum RunPodLanguages {
    static let whisperXVersion = "3.8.6"
    static let all: [ProviderLanguage] = [
        ProviderLanguage(code: "en", name: "English"),
        ProviderLanguage(code: "zh-cn", name: "Chinese (Simplified)"),
        ProviderLanguage(code: "zh-tw", name: "Chinese (Traditional)"),
        ProviderLanguage(code: "ja", name: "Japanese"),
        ProviderLanguage(code: "ko", name: "Korean"),
        ProviderLanguage(code: "es", name: "Spanish"),
        ProviderLanguage(code: "fr", name: "French"),
        ProviderLanguage(code: "de", name: "German"),
        ProviderLanguage(code: "pt", name: "Portuguese"),
        ProviderLanguage(code: "ru", name: "Russian"),
        ProviderLanguage(code: "ar", name: "Arabic"),
    ]
}
